name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: headlights

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for MySQL to be ready
      run: |
        until mysql -h mysql -u root -proot -e 'SHOW DATABASES;'; do
          echo "Waiting for database to be ready..."
          sleep 3
        done
    - name: Run Tests
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/headlights
      run: |
        python manage.py test
